import Head from "next/head"
import Header from "organisms/Header"
import TopBar from "organisms/TopBar"
import NavBar from "organisms/NavBar"
import Newsletter from "organisms/Newsletter"
import Footer from "organisms/Footer"

import "styles/styles.scss"

const MyApp = ({ Component, pageProps, menu }) => {
    return (
        <div className={"app--container"}>
            <Head>
                <title>DiloconFlores.com</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopBar />
            <Header />
            <NavBar />
            <main className={"app--main"}>
                <Component {...pageProps} menu={menu} />
            </main>
            <Newsletter />
            <Footer />
        </div>
    )
}

// MyApp.getInitialProps = async (appContext) => {
//   const {req} = appContext.ctx;
//   const appProps = await App.getInitialProps(appContext);

//   try {
//     const store = await fetch(()))
//     const { menu } = await store.json();
//     console.log('req', req)
//     if(!req) localStorage.setItem('store-menu', menu)
//     return { ...appProps, menu }
//   } catch (e) {
//     console.log(e)
//     return { ...appProps }
//   }

// }

export default MyApp
