import Head from "next/head"
import Image from "next/image"

import "styles/styles.scss"

const MyApp = ({ Component, pageProps }) => {
    return (
        <div className={"app--container"}>
            <Head>
                <title>DiloconFlores.com</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={"app--main"}>
                <Component {...pageProps} />
            </main>
            <footer className={"app--footer"}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={"app--logo"}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default MyApp
