import Head from "next/head"
import Image from "next/image"
import Header from "organisms/Header"
import TopBar from "organisms/TopBar"
import NavBar from "organisms/NavBar"
import Footer from "organisms/Footer"

import "styles/styles.scss"

const MyApp = ({ Component, pageProps }) => {
    return (
        <div className={"app--container"}>
            <Head>
                <title>DiloconFlores.com</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopBar />
            <Header />
            <NavBar />
            <main className={"app--main"}>
                <Component {...pageProps} />
            </main>
            <Footer />
        </div>
    )
}

export default MyApp
